version: "3.9"

services:

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
    - 3000:3000

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

    volumes:
#    - ./structure:/docker-entrypoint-initdb.d  # Инициализация структуры БД *.sql, *.sh
    - .data:/var/lib/postgresql/data
    - ./scripts:/scripts

    ports:
    - "5432:5432"
    expose:
      - 5432

    healthcheck:
      test: "pg_isready -U user -d test_db"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "4G"

  postgres-exporter:
    container_name: exporter
    image: prometheuscommunity/postgres-exporter
    ports:
    - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres:5432/test_db?sslmode=disable"
    links:
      - postgres
      - prometheus

