version: "3.9"

services:
  postgres:
    image: postgres:14.5
    container_name: postgres_container
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
    - ./structure:/docker-entrypoint-initdb.d  # Инициализация структуры БД *.sql, *.sh
    - .:/var/lib/postgresql/data
    - ./postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf

    ports:
    - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: 1
          memory: "4G"

  pgadmin:
    image: dpage/pgadmin4:6.0
    container_name: pgadmin_container

    environment:
      PGADMIN_DEFAULT_EMAIL: "user@test.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"

    volumes:
      - ./pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"

    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

    networks:
      - postgres

networks:
  postgres:
    driver: bridge